# Generated by Django 5.2.5 on 2025-08-21 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0004_alter_task_due_date_alter_task_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
