# Generated by Django 5.2.5 on 2025-08-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0005_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=35),
        ),
    ]
