# Generated by Django 5.2.5 on 2025-08-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
