# Generated by Django 5.2.5 on 2025-08-17 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_board', '0002_rename_owner_id_board_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
